apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: ops
    enable_velero: 'true'
    enable_app: 'false'
  annotations:
    aws_cluster_name: hub-cluster
    k8s_service_host: 2479598A0B25A29A79AAFFEB52D256F4.gr7.us-east-1.eks.amazonaws.com
    velero_bucket_name: gitopscon-na-24-velero-backups-hub
    velero_iam_role_arn: arn:aws:iam::015299085168:role/velero-role-67062f8
  name: hub-cluster-secret
  namespace: argocd
type: Opaque
stringData:
  name: hub
  server: https://kubernetes.default.svc
data:
  config: ewogICJ0bHNDbGllbnRDb25maWciOiB7CiAgICAiaW5zZWN1cmUiOiBmYWxzZQogIH0KfQo=
