---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-aws-velero
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: velero
                # anything not staging or prod use this version
                addonChartVersion: 6.0.0
                addonChartRepository: https://vmware-tanzu.github.io/helm-charts
              selector:
                matchExpressions:
                  - key: enable_velero
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: 6.0.0
          - clusters:
              selector:
                matchLabels:
                  environment: prod
              values:
                addonChartVersion: 6.0.0
  template:
    metadata:
      name: addon-{{name}}-{{values.addonChart}}
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/csantanapr/gitopscon-2024-na-demo-carlos'
          targetRevision: 'HEAD'
          ref: values
        - chart: '{{values.addonChart}}'
          repoURL: '{{values.addonChartRepository}}'
          targetRevision: '{{values.addonChartVersion}}'
          helm:
            releaseName: '{{values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/gitops/charts/{{values.addonChart}}/values.yaml
              - $values/gitops/environments/{{metadata.labels.environment}}/addons/{{values.addonChart}}/values.yaml
              - $values/gitops/clusters/{{name}}/addons/{{values.addonChart}}/values.yaml
            values: |
              configuration:
                backupStorageLocation:
                - name: default
                  provider: aws
                  bucket: {{metadata.annotations.velero_bucket_name}}
                  config:
                    region: us-east-1
                volumeSnapshotLocation:
                - name: default
                  provider: aws
                  config:
                    region: us-east-1
              serviceAccount:
                server:
                  name: velero
                  annotations:
                    eks.amazonaws.com/role-arn: {{metadata.annotations.velero_iam_role_arn}}
              initContainers:
              - name: velero-plugin-for-aws
                image: velero/velero-plugin-for-aws:v1.7.1
                imagePullPolicy: IfNotPresent
                volumeMounts:
                  - mountPath: /target
                    name: plugins
      destination:
        namespace: 'velero'
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.